import { getAllPosts, PostMeta } from "@/src/postApi"
import Head from "next/head"
import Postcard from "./components/Postcard"

export default function Home({ posts }: { posts: PostMeta[] }) {
  return (
    <>
      <Head>
        <title>i701 | Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className={`space-y-4`}>
          <h1 className="text-2xl md:text-4xl font-bold text-orange-600">
            <span className="accent-line ">Hello </span>
          </h1>
          <p className="dark:text-gray-400 md:text-base text-sm">
            Welcome to by blog!
          </p>

          {posts.map((post) => (
            <Postcard key={post.title} post={post} />
          ))}
        </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const posts = getAllPosts()
    .slice(0, 9)
    .map((post) => post.meta)
  console.log(posts)
  return { props: { posts } }
}
